# Generated by Django 5.0.7 on 2024-08-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_skill_name_skill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bios/'),
        ),
    ]
